# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2be8b95ab31695c0d8f1f17a70568eeb81671676dbfca47d879253b1448476240fbb247d501c43bd56f0fc756a3807051e9e48e220fea91cb432f257f42dd6a2

test:
  secret_key_base: d4693175e25d91f3e11072035a745243396e1a45862c7647bc87c81b4e8e6b21436113d394c9b6c5fe7ee463bed11b37365a38707207885f44315e268ff98458

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
